name: easy_dynamic_link
description: Hanlding Firebase Dynamic Link Easily
version: 0.0.1
publisher : 312tkdldjs@gmail.com
homepage: https://github.com/kimtaeoug
repository: https://github.com/kimtaeoug/easy_dynamic_link

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_dynamic_links: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

